# Generated by Django 5.2.3 on 2026-09-09 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_amenity_rename_pricepernight_listing_price_per_night_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyoffer',
            name='occupants',
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='max_occupants',
            field=models.PositiveIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='min_occupants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='bed',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='shower',
            field=models.PositiveIntegerField(),
        ),
    ]
